cmake_minimum_required(VERSION 3.10)
project(DirectXEngine)

set(SOURCE_FILES
    src\sysFrame\System\Json\Json.cpp
    src\sysFrame\Framework\Adapter.cpp
    AudioAnther.cpp
    src\sysFrame\Object\Camera\CameraManager.cpp
    src\sysFrame\Object\Light\DirectionalLight\DirectionalLight.cpp
    src\sysFrame\Object\Light\PointLight\PointLight.cpp
    src\sysFrame\Object\Light\SpotLight\SpotLight.cpp
    src\sysFrame\Scene\Effect\SceneChanger.cpp
    src\sysFrame\Scene\Effect\Fade.cpp
    Game\GameScene\GameScene.cpp
    Game\SceneFactory.cpp
    src\sysFrame\System\ImGui\ImGuiCommand.cpp
    src\sysFrame\Scene\Effect\ISceneEffect.cpp
    src\sysFrame\System\Math\Easing.cpp
    src\sysFrame\Object\ColorEditor.cpp
    src\sysFrame\Object\Particle\Particle2d.cpp
    src\sysFrame\Object\Particle\Emitter2d.cpp
    src\sysFrame\Object\Particle\ParticleCommon.cpp
    src\sysFrame\Object\Particle\ParticleManager.cpp
    src\sysFrame\Scene\AbstractSceneFactory.cpp
    src\sysFrame\Scene\SceneManager.cpp
    src\sysFrame\Scene\BaseScene.cpp
    src\sysFrame\System\File\File.cpp
    src\sysFrame\Framework\Framework.cpp
    src\sysFrame\DirectX\Lighting\LightManager.cpp
    src\sysFrame\DirectX\Model\ModelManager.cpp
    src\sysFrame\Object\Model\Mesh\Mesh.cpp
    src\sysFrame\Object\Model\Mesh\MeshCommon.cpp
    src\sysFrame\Object\Model\Model.cpp
    src\sysFrame\Object\Model\ModelCommon.cpp
    src\sysFrame\Object\Sprite\Sprite.cpp
    src\sysFrame\Object\Sprite\SpriteCommon.cpp
    src\sysFrame\System\Loader.cpp
    src\sysFrame\DirectX\Heap\SRVManager.cpp
    src\sysFrame\DirectX\Texture\TextureManager.cpp
    src\sysFrame\Engine\Engine.cpp
    src\sysFrame\DirectX\Util\D3DResourceLeakChecker.cpp
    src\sysFrame\Engine\EngineDebug.cpp
    src\sysFrame\System\ImGui\ImGuiManager.cpp
    src\sysFrame\Object\Camera\Camera.cpp
    src\sysFrame\DirectX\Heap\Heap.cpp
    src\sysFrame\DirectX\DirectXCommon.cpp
    main.cpp
    src\sysFrame\Application\WinApp.cpp
    src\sysFrame\DirectX\Pipeline\GraphicsPipeline.cpp
    src\sysFrame\DirectX\Shader\Shader.cpp
    src\sysFrame\System\Input\Input.cpp
    src\sysFrame\System\Log\Log.cpp
    src\sysFrame\System\Math\MathUtils.cpp
    src\sysFrame\System\Math\Vector2.cpp
    src\sysFrame\System\Math\Vector3.cpp
    src\sysFrame\System\SingletonFinalizer\SingletonFinalizer.cpp
    src\sysFrame\System\Sound\Audio.cpp
    src\sysFrame\System\System.cpp
    src\sysFrame\System\Window\Window.cpp
    src\sysFrame\System\Math\WorldTransform.cpp
    src\sysFrame\System\Thread\ThreadManager.cpp
    src\sysFrame\System\Singleton\Singleton.h
    src\sysFrame\System\Json\Json.h
    src\externals\MagicEnum\magic_enum.hpp
    src\externals\miniaudio\miniaudio.h
    src\sysFrame\Object\Light\RawLight.h
    src\sysFrame\Framework\Adapter.h
    AudioAnther.h
    src\sysFrame\Object\Camera\CameraManager.h
    src\sysFrame\Scene\Effect\SceneChanger.h
    src\sysFrame\Scene\Effect\Fade.h
    src\sysFrame\Scene\Effect\ISceneEffect.h
    src\sysFrame\System\Math\Easing.h
    src\sysFrame\Object\ColorEditor.h
    Game\Element\ElementStatus.h
    Game\GameScene\GameScene.h
    Game\SceneFactory.h
    src\sysFrame\Object\Particle\Particle2d.h
    src\sysFrame\Object\Particle\Emitter2d.h
    src\sysFrame\Object\Particle\ParticleCommon.h
    src\sysFrame\Object\Particle\ParticleManager.h
    src\sysFrame\System\ImGui\ImGuiCommand.h
    src\externals\json\include\nlohmann\adl_serializer.hpp
    src\externals\json\include\nlohmann\byte_container_with_subtype.hpp
    src\externals\json\include\nlohmann\detail\abi_macros.hpp
    src\externals\json\include\nlohmann\detail\conversions\from_json.hpp
    src\externals\json\include\nlohmann\detail\conversions\to_chars.hpp
    src\externals\json\include\nlohmann\detail\conversions\to_json.hpp
    src\externals\json\include\nlohmann\detail\exceptions.hpp
    src\externals\json\include\nlohmann\detail\hash.hpp
    src\externals\json\include\nlohmann\detail\input\binary_reader.hpp
    src\externals\json\include\nlohmann\detail\input\input_adapters.hpp
    src\externals\json\include\nlohmann\detail\input\json_sax.hpp
    src\externals\json\include\nlohmann\detail\input\lexer.hpp
    src\externals\json\include\nlohmann\detail\input\parser.hpp
    src\externals\json\include\nlohmann\detail\input\position_t.hpp
    src\externals\json\include\nlohmann\detail\iterators\internal_iterator.hpp
    src\externals\json\include\nlohmann\detail\iterators\iteration_proxy.hpp
    src\externals\json\include\nlohmann\detail\iterators\iterator_traits.hpp
    src\externals\json\include\nlohmann\detail\iterators\iter_impl.hpp
    src\externals\json\include\nlohmann\detail\iterators\json_reverse_iterator.hpp
    src\externals\json\include\nlohmann\detail\iterators\primitive_iterator.hpp
    src\externals\json\include\nlohmann\detail\json_custom_base_class.hpp
    src\externals\json\include\nlohmann\detail\json_pointer.hpp
    src\externals\json\include\nlohmann\detail\json_ref.hpp
    src\externals\json\include\nlohmann\detail\macro_scope.hpp
    src\externals\json\include\nlohmann\detail\macro_unscope.hpp
    src\externals\json\include\nlohmann\detail\meta\call_std\begin.hpp
    src\externals\json\include\nlohmann\detail\meta\call_std\end.hpp
    src\externals\json\include\nlohmann\detail\meta\cpp_future.hpp
    src\externals\json\include\nlohmann\detail\meta\detected.hpp
    src\externals\json\include\nlohmann\detail\meta\identity_tag.hpp
    src\externals\json\include\nlohmann\detail\meta\is_sax.hpp
    src\externals\json\include\nlohmann\detail\meta\std_fs.hpp
    src\externals\json\include\nlohmann\detail\meta\type_traits.hpp
    src\externals\json\include\nlohmann\detail\meta\void_t.hpp
    src\externals\json\include\nlohmann\detail\output\binary_writer.hpp
    src\externals\json\include\nlohmann\detail\output\output_adapters.hpp
    src\externals\json\include\nlohmann\detail\output\serializer.hpp
    src\externals\json\include\nlohmann\detail\string_concat.hpp
    src\externals\json\include\nlohmann\detail\string_escape.hpp
    src\externals\json\include\nlohmann\detail\value_t.hpp
    src\externals\json\include\nlohmann\json.hpp
    src\externals\json\include\nlohmann\json_fwd.hpp
    src\externals\json\include\nlohmann\ordered_map.hpp
    src\externals\json\include\nlohmann\thirdparty\hedley\hedley.hpp
    src\externals\json\include\nlohmann\thirdparty\hedley\hedley_undef.hpp
    src\externals\json\single_include\nlohmann\json.hpp
    src\externals\json\single_include\nlohmann\json_fwd.hpp
    src\sysFrame\Object\ICollider.h
    src\sysFrame\Scene\AbstractSceneFactory.h
    src\sysFrame\Scene\SceneManager.h
    src\sysFrame\Scene\BaseScene.h
    src\sysFrame\System\File\File.h
    Game\Game.h
    src\sysFrame\Framework\Framework.h
    src\sysFrame\DirectX\Lighting\LightManager.h
    src\sysFrame\DirectX\Model\ModelManager.h
    src\sysFrame\Object\Light\DirectionalLight\DirectionalLight.h
    src\sysFrame\Object\Light\PointLight\PointLight.h
    src\sysFrame\Object\Light\SpotLight\SpotLight.h
    src\sysFrame\Object\Model\Mesh\MeshCommon.h
    src\sysFrame\Object\Model\Mesh\Mesh.h
    src\sysFrame\Object\Model\ModelCommon.h
    src\sysFrame\Object\Model\Model.h
    src\sysFrame\Object\Sprite\Sprite.h
    src\sysFrame\Object\Sprite\SpriteCommon.h
    src\sysFrame\System\Loader.h
    src\sysFrame\Engine\EngineDebug.h
    src\sysFrame\DirectX\Heap\SRVManager.h
    src\sysFrame\DirectX\Texture\TextureManager.h
    src\sysFrame\Engine\Engine.h
    src\sysFrame\DirectX\Util\D3DResourceLeakChecker.h
    src\sysFrame\System\ImGui\ImGuiManager.h
    src\sysFrame\Object\Camera\Camera.h
    src\sysFrame\DirectX\Heap\Heap.h
    src\sysFrame\DirectX\DirectXCommon.h
    src\sysFrame\Application\WinApp.h
    src\sysFrame\DirectX\Pipeline\GraphicsPipeline.h
    src\sysFrame\DirectX\Shader\Shader.h
    src\sysFrame\Object\Object.h
    src\sysFrame\System\Input\Input.h
    src\sysFrame\System\Log\Log.h
    src\sysFrame\System\Math\Material.h
    src\sysFrame\System\Math\MathUtils.h
    src\sysFrame\System\Math\Matrix.h
    src\sysFrame\System\Math\Transform.h
    src\sysFrame\System\Math\ModelTransformation.h
    src\sysFrame\System\Math\Vector2.h
    src\sysFrame\System\Math\Vector3.h
    src\sysFrame\System\Math\Vector4.h
    src\sysFrame\System\SingletonFinalizer\SingletonFinalizer.h
    src\sysFrame\System\Sound\Audio.h
    src\sysFrame\System\System.h
    src\sysFrame\System\Window\Window.h
    src\sysFrame\System\Math\VertexData.h
    src\sysFrame\System\Math\WorldTransform.h
    src\sysFrame\System\Thread\ThreadManager.h
)

add_executable(${PROJECT_NAME} ${SOURCE_FILES})
