sonar.projectKey=sqp_56a5c79013a75cb9b4013552644ac10a3f12f179
sonar.projectName=Engine
sonar.sources=src
sonar.cfamily.build-wrapper-output=build_wrapper_output
sonar.host.url=http://localhost:9000
sonar.login=squ_6850f70be77b4e794757340a352721df36ef1477